services:
  frontend:
    build: ./frontend
    ports:
      - "11110:80"
    depends_on:
      - backend
    networks:
      - aqua-network

  backend:
    build: ./backend
    ports:
      - "11111:5000"
    environment:
      - NODE_ENV=demo
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    networks:
      - aqua-network

networks:
  aqua-network:
    driver: bridge
