services:
  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
    ports:
      - "11110:80"
    environment:
      - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
    depends_on:
      - backend
    networks:
      - aqua-network

  backend:
    build: ./backend
    ports:
      - "11111:5000"
    environment:
      - NODE_ENV=demo
    networks:
      - aqua-network

networks:
  aqua-network:
    driver: bridge
